name: 'Check commit message format'
on:
  pull_request:
  merge_group:

jobs:
  check-commit-message:
    name: Check commit message format
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'merge_group' }}
    steps:
      - name: Check for commit type
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '(fix|feat|chore|refactor)[:](.+)'
          error: 'Commit message should look like: <category>: <description>, where category is one of: fix, feat, chore, refactor.'
